name: Extract ≥10-acre parcels

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1'          # Mondays 06:00 CST (optional)

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r python/requirements.txt

      # --- discover the zip url on the data-downloads page ---
      - name: Find latest Preliminary Roll URL
        id: findzip
        run: |
          PAGE="https://taylor-cad.org/data-downloads/"
          # Pull the page, grep the first .zip link that matches the phrase we want
          ZIP_URL=$(curl -sSL "$PAGE" \
            | grep -Eo 'https:[^"]*Preliminary[^\"]*All_Property_Types[^"]*\\.zip' \
            | head -n1)
          echo "ZIP_URL=$ZIP_URL"
          echo "zip_url=$ZIP_URL" >> "$GITHUB_OUTPUT"

      # --- download the discovered zip ---
      - name: Download roll.zip
        run: |
          curl -L -o roll.zip "${{ steps.findzip.outputs.zip_url }}"

      # --- run the parser ---
      - name: Run parser
        run: python python/taylor_parcel_parser.py roll.zip

      # --- save csv artifact ---
      - uses: actions/upload-artifact@v4
        with:
          name: taylor-10plus-acres
          path: taylor_10plus_acres.csv
