name: Extract ≥10-acre parcels

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1'        # weekly Monday 06:00 CST

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r python/requirements.txt

      # ── NEW, broader regex ───────────────────────────────────────
      - name: Find latest Preliminary Roll URL
        id: findzip
        run: |
          PAGE="https://taylor-cad.org/data-downloads/"
          HTML=$(curl -sSL "$PAGE")
          REL=$(echo "$HTML" \
                | grep -Eo 'href="[^"]*Preliminary[^"]*\.zip"' \
                | head -n1 \
                | cut -d'"' -f2)
          if [[ -z "$REL" ]]; then
            echo "::error::Could not locate ZIP link on page"
            exit 1
          fi
          [[ "$REL" == http* ]] && ZIP_URL="$REL" || ZIP_URL="https://taylor-cad.org$REL"
          echo "ZIP_URL=$ZIP_URL"
          echo "zip_url=$ZIP_URL" >> "$GITHUB_OUTPUT"

      - name: Download roll.zip
        run: curl -L -o roll.zip "${{ steps.findzip.outputs.zip_url }}"

      - name: Verify ZIP integrity
        run: unzip -tqq roll.zip

      - name: Run parser
        run: python python/taylor_parcel_parser.py roll.zip

      - uses: actions/upload-artifact@v4
        with:
          name: taylor-10plus-acres
          path: taylor_10plus_acres.csv
